application:
  start_env: INT
cleanup_interval: 300
landing_page:
  description: Reveal the hidden paths of Kafka traces, gRPC integrations, and blueprint
    secrets. Track every movement, discover every connection.
  enabled: true
  subtitle: Expecto Debuggius
  title: Marauder's Map
logging:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
max_traces: 1000
message_processing:
  batch_size: 100
  decode_errors: log
  processing_timeout: 30
mock_data:
  enabled: true
  message_interval: 2.0
  topics_rotation: true
  traces_per_hour: 50
tabs:
  blueprint_creator:
    description: Chart new territories and verify Redis chamber secrets
    enabled: true
    title: Blueprint Creator
  grpc_integration:
    description: Unlock secret passages to gRPC services and test their defenses
    enabled: true
    title: gRPC Integration
  trace_viewer:
    description: Track footsteps through Kafka message corridors and reveal hidden
      paths
    enabled: true
    title: Trace Viewer
topic_monitoring:
  activate_all_on_startup: true
trace_header_field: traceparent
web_server:
  cors_enabled: true
  debug: true
  host: 0.0.0.0
  port: 8001
