# Application configuration
trace_header_field: "trace_id"  # Configurable trace header field name
max_traces: 1000                 # Maximum traces to retain in memory
cleanup_interval: 300            # Seconds between cleanup cycles

# Web server settings
web_server:
  host: "0.0.0.0"
  port: 8001
  debug: true
  cors_enabled: true

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Message processing settings
message_processing:
  batch_size: 100              # Messages to process in batch
  processing_timeout: 30       # Seconds to wait for message processing
  decode_errors: "ignore"      # ignore, raise, log

# Mock data settings for development
mock_data:
  enabled: true
  message_interval: 2.0        # Seconds between mock messages
  traces_per_hour: 50         # Number of traces to generate per hour
  topics_rotation: true       # Rotate through different topics

# Topic monitoring settings
topic_monitoring:
  activate_all_on_startup: true  # Whether to monitor all configured topics on startup

application:
  start_env: INT

# Application tabs configuration
tabs:
  trace_viewer:
    enabled: true
    title: "Trace Viewer"
    description: "Kafka message flow visualization and tracing"
  grpc_integration:
    enabled: true
    title: "gRPC Integration"
    description: "gRPC service integration and testing"
  blueprint_creator:
    enabled: true
    title: "Blueprint Creator"
    description: "Blueprint management and Redis verification"

# Landing page configuration
landing_page:
  enabled: true
  title: "Kafka Monitor Dashboard"
  subtitle: "Comprehensive monitoring and management platform"
  description: "Monitor Kafka traces, manage gRPC integrations, and create blueprints with Redis verification"