# PROD Environment Configuration
name: "PROD"
description: "Production Environment"

# Kafka Configuration for this environment
kafka:
  bootstrap_servers: "prod-kafka.example.com:9092"
  security_protocol: "SASL_SSL"
  sasl_mechanism: "SCRAM-SHA-256"
  username: "prod-kafka-user"
  password: "prod-kafka-password"

grpc_services:
  ingress_server:
    url: "prod-ingress.example.com:443"
    secure: true
    timeout: 45
    
  asset_storage:
    # Multiple URLs for asset storage with reader/writer labels
    urls:
      reader: "prod-assets-reader.example.com:443"
      writer: "prod-assets-writer.example.com:443"
    secure: true
    timeout: 45

# Note: gRPC Credentials are provided at runtime via UI
# and stored in memory only - never in config files