# PROD Environment Configuration
name: "PROD"
description: "Production Environment"

# Kafka Configuration for this environment
kafka:
  bootstrap_servers: "kafka-prod.example.com:9092"
  security_protocol: "SASL_SSL"
  sasl_mechanism: "SCRAM-SHA-512"
  username: "kafka-prod-user"
  password: "kafka-prod-password"

grpc_services:
  ingress_server:
    url: "ingress-prod.example.com:443"
    secure: true
    timeout: 30
    # Path to the service definition proto file
    service_proto: "eadp/cadie/ingressserver/v1/ingress_service.proto"
    
  asset_storage:
    # Multiple URLs for asset storage with reader/writer labels
    urls:
      reader: "asset-storage-prod-reader.example.com:443"
      writer: "asset-storage-prod-writer.example.com:443"
    secure: true
    timeout: 30
    # Path to the service definition proto file
    service_proto: "eadp/cadie/shared/storageinterface/v1/storage_service_admin.proto"

# Blueprint Server Configuration
blueprint_server:
  base_url: "https://blueprint-prod.example.com"
  validate_path: "/api/v1/blueprint/validate"
  activate_path: "/api/v1/blueprint/activate"
  auth_header_name: "Authorization"
  auth_header_value: "Bearer prod-api-token"

# Note: gRPC Credentials are provided at runtime via UI
# and stored in memory only - never in config files