# TEST Environment Configuration
name: "TEST"
description: "Test Environment"

# Kafka Configuration for this environment
kafka:
  bootstrap_servers: "kafka-test.example.com:9092"
  security_protocol: "SASL_SSL"
  sasl_mechanism: "SCRAM-SHA-512"
  username: "kafka-test-user"
  password: "kafka-test-password"

grpc_services:
  ingress_server:
    url: "ingress-test.example.com:443"
    secure: true
    timeout: 30
    # Path to the service definition proto file
    service_proto: "eadp/cadie/ingressserver/v1/ingress_service.proto"
    
  asset_storage:
    # Multiple URLs for asset storage with reader/writer labels
    urls:
      reader: "asset-storage-test-reader.example.com:443"
      writer: "asset-storage-test-writer.example.com:443"
    secure: true
    timeout: 30
    # Path to the service definition proto file
    service_proto: "eadp/cadie/shared/storageinterface/v1/storage_service_admin.proto"

# Blueprint Server Configuration
blueprint_server:
  base_url: "https://blueprint-test.example.com"
  validate_path: "/validate/{namespace}"
  activate_path: "/activate/{namespace}"
  auth_header_name: "Authorization"
  auth_header_value: "Bearer test-api-token"

# Redis Configuration for Blueprint Verification
redis:
  host: "redis-test.example.com"
  port: 6380
  token: "test-redis-auth-token-here"
  ca_cert_path: "config/redis-ca.pem"
  connection_timeout: 10
  socket_timeout: 10
  retry_on_timeout: true
  health_check_interval: 30

# Note: gRPC Credentials are provided at runtime via UI
# and stored in memory only - never in config files