# TEST Environment Configuration
name: "TEST"
description: "Test Environment"

# Kafka Configuration for this environment
kafka:
  bootstrap_servers: "test-kafka.example.com:9092"
  security_protocol: "SASL_SSL"
  sasl_mechanism: "SCRAM-SHA-256"
  username: "test-kafka-user"
  password: "test-kafka-password"

grpc_services:
  ingress_server:
    url: "test-ingress.example.com:443"
    secure: true
    timeout: 30
    
  asset_storage:
    # Multiple URLs for asset storage with reader/writer labels
    urls:
      reader: "test-assets-reader.example.com:443"
      writer: "test-assets-writer.example.com:443"
    secure: true
    timeout: 30

# Note: gRPC Credentials are provided at runtime via UI
# and stored in memory only - never in config files